services:
  other-api:
    build:
      context: ../ # 指定Dockerfile的目录
      dockerfile: Dockerfile        # Dockerfile的名称（如果不是默认的）
    image: other-api:v1.1
    container_name: oj-other-api
    networks:
      - oj-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8890:8890" # 假设您的Go应用监听在8090端口
    volumes:
      - ./:/app/other/etc
      - ./logs:/app/other/logs

networks:
  oj-network:
    external: true