// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userservice

import (
	"context"

	"oj-micro/users/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUserLoginReq        = pb.AddUserLoginReq
	AddUserLoginResp       = pb.AddUserLoginResp
	DelUserLoginReq        = pb.DelUserLoginReq
	DelUserLoginResp       = pb.DelUserLoginResp
	GetUserLoginByIdReq    = pb.GetUserLoginByIdReq
	GetUserLoginByIdResp   = pb.GetUserLoginByIdResp
	GetUserProfileByIdReq  = pb.GetUserProfileByIdReq
	GetUserProfileByIdResp = pb.GetUserProfileByIdResp
	LoginUserReq           = pb.LoginUserReq
	LoginUserResp          = pb.LoginUserResp
	LoginWithCodeReq       = pb.LoginWithCodeReq
	PartialUpdateUserReq   = pb.PartialUpdateUserReq
	PartialUpdateUserResp  = pb.PartialUpdateUserResp
	SearchUserLoginReq     = pb.SearchUserLoginReq
	SearchUserLoginResp    = pb.SearchUserLoginResp
	UpdateUserLoginReq     = pb.UpdateUserLoginReq
	UpdateUserLoginResp    = pb.UpdateUserLoginResp
	UpdateUserProfileReq   = pb.UpdateUserProfileReq
	UpdateUserProfileResp  = pb.UpdateUserProfileResp
	UserLogin              = pb.UserLogin
	UserProfile            = pb.UserProfile

	UserService interface {
		// -----------------------用户认证授权-----------------------
		AddUserLogin(ctx context.Context, in *AddUserLoginReq, opts ...grpc.CallOption) (*AddUserLoginResp, error)
		UpdateUserLogin(ctx context.Context, in *UpdateUserLoginReq, opts ...grpc.CallOption) (*UpdateUserLoginResp, error)
		DelUserLogin(ctx context.Context, in *DelUserLoginReq, opts ...grpc.CallOption) (*DelUserLoginResp, error)
		GetUserLoginById(ctx context.Context, in *GetUserLoginByIdReq, opts ...grpc.CallOption) (*GetUserLoginByIdResp, error)
		SearchUserLogin(ctx context.Context, in *SearchUserLoginReq, opts ...grpc.CallOption) (*SearchUserLoginResp, error)
		LoginUser(ctx context.Context, in *LoginUserReq, opts ...grpc.CallOption) (*LoginUserResp, error)
		LoginWithCode(ctx context.Context, in *LoginWithCodeReq, opts ...grpc.CallOption) (*LoginUserResp, error)
		PartialUpdateUser(ctx context.Context, in *PartialUpdateUserReq, opts ...grpc.CallOption) (*PartialUpdateUserResp, error)
		// -----------------------用户信息-----------------------
		UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileResp, error)
		// rpc DelUserProfile(DelUserProfileReq) returns (DelUserProfileResp);
		GetUserProfileById(ctx context.Context, in *GetUserProfileByIdReq, opts ...grpc.CallOption) (*GetUserProfileByIdResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// -----------------------用户认证授权-----------------------
func (m *defaultUserService) AddUserLogin(ctx context.Context, in *AddUserLoginReq, opts ...grpc.CallOption) (*AddUserLoginResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.AddUserLogin(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserLogin(ctx context.Context, in *UpdateUserLoginReq, opts ...grpc.CallOption) (*UpdateUserLoginResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserLogin(ctx, in, opts...)
}

func (m *defaultUserService) DelUserLogin(ctx context.Context, in *DelUserLoginReq, opts ...grpc.CallOption) (*DelUserLoginResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.DelUserLogin(ctx, in, opts...)
}

func (m *defaultUserService) GetUserLoginById(ctx context.Context, in *GetUserLoginByIdReq, opts ...grpc.CallOption) (*GetUserLoginByIdResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserLoginById(ctx, in, opts...)
}

func (m *defaultUserService) SearchUserLogin(ctx context.Context, in *SearchUserLoginReq, opts ...grpc.CallOption) (*SearchUserLoginResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.SearchUserLogin(ctx, in, opts...)
}

func (m *defaultUserService) LoginUser(ctx context.Context, in *LoginUserReq, opts ...grpc.CallOption) (*LoginUserResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.LoginUser(ctx, in, opts...)
}

func (m *defaultUserService) LoginWithCode(ctx context.Context, in *LoginWithCodeReq, opts ...grpc.CallOption) (*LoginUserResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.LoginWithCode(ctx, in, opts...)
}

func (m *defaultUserService) PartialUpdateUser(ctx context.Context, in *PartialUpdateUserReq, opts ...grpc.CallOption) (*PartialUpdateUserResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.PartialUpdateUser(ctx, in, opts...)
}

// -----------------------用户信息-----------------------
func (m *defaultUserService) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserProfile(ctx, in, opts...)
}

// rpc DelUserProfile(DelUserProfileReq) returns (DelUserProfileResp);
func (m *defaultUserService) GetUserProfileById(ctx context.Context, in *GetUserProfileByIdReq, opts ...grpc.CallOption) (*GetUserProfileByIdResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserProfileById(ctx, in, opts...)
}
