services:
  users-rpc:
    build:
      context: ../cmd # 指定Dockerfile的目录
      dockerfile: Dockerfile-users_rpc             # Dockerfile的名称（如果不是默认的）
    image: users-rpc:v1.2                # 指定构建完成后的镜像名称
    container_name: oj-users-rpc
    networks:
      - oj-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    ports:
#      - "8080:8080"
    volumes:
      - ./:/app/users/cmd/rpc/etc
      - ./logs/rpc:/app/users/cmd/rpc/logs

  users-api:
    build:
      context: ../cmd # 指定Dockerfile的目录
      dockerfile: Dockerfile-users_api             # Dockerfile的名称（如果不是默认的）
    image: users-api:v1.3
    container_name: oj-users-api
    networks:
      - oj-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8888:8888" # 假设您的Go应用监听在8888端口
    depends_on:
      - users-rpc
    volumes:
      - ./:/app/users/cmd/api/etc
      - ./logs/api:/app/users/cmd/api/logs

networks:
  oj-network:
    external: true


