apiVersion: v1
kind: Service
metadata:
  name: nats-server
spec:
  type: ClusterIP  # 确保使用ClusterIP类型
  ports:
    - port: 4222        # Service暴露的端口
      targetPort: 4222  # nats的端口
#  clusterIP: None       # 这是一个Headless Service
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nats-server    # 必须与 Service 名称相同
subsets:
  - addresses:
      - ip: 8.134.142.46  # 替换为你的主库实际IP
    ports:
      - port: 4222