services:
  etcd-local:
    image: bitnami/etcd:latest
    container_name: etcd-local
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://host.docker.internal:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379  # 监听所有接口
