// Code generated by goctl. DO NOT EDIT.
package types

type AddTestCaseRequest struct {
	ProblemId int64 `form:"problem_id,range=[1:]"`
}

type AddTestCaseResponse struct {
	TestCase struct {
		TestId             int64
		ProblemId          int64
		TestGroup          int64
		TestInputFileName  string
		TestOutputFileName string
		UpdateAt           int64
	} `json:"test_case"`
}

type DeleteTestCaseRequest struct {
	TestId int64 `path:"test_id"`
}

type DeleteTestCaseResponse struct {
}

type TestCases struct {
	TestId             int64
	ProblemId          int64
	TestGroup          int64
	TestInputFileName  string
	TestOutputFileName string
	UpdateAt           int64
}

type UpdateUserCoverRequest struct {
	ID int64 `path:"user_id,range=[1:]"`
}

type UpdateUserResponse struct {
}
