// Code generated by goctl. DO NOT EDIT.
package types

type AddTestCaseRequest struct {
	ProblemId int64 `form:"problem_id,range=[1:]"`
}

type AddTestCaseResponse struct {
}

type DeleteTestCaseRequest struct {
	TestId int64 `path:"test_id"`
}

type DeleteTestCaseResponse struct {
}

type UpdateUserCoverRequest struct {
	ID int64 `path:"user_id,range=[1:]"`
}

type UpdateUserResponse struct {
}
