// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	upload_file "oj-micro/other/internal/handler/upload_file"
	"oj-micro/other/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 添加测试用例
				Method:  http.MethodPost,
				Path:    "/test_cases",
				Handler: upload_file.AddTestCaseHandler(serverCtx),
			},
			{
				// 删除测试用例
				Method:  http.MethodDelete,
				Path:    "/test_cases/:test_id",
				Handler: upload_file.DeleteTestCaseHandler(serverCtx),
			},
			{
				// 更新用户头像
				Method:  http.MethodPost,
				Path:    "/users/:user_id/cover",
				Handler: upload_file.UpdateUserCoverHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api3"),
	)
}
