services:
  nginx:
    image: nginx:stable
    container_name: oj-nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    volumes:
      - ./templates:/etc/nginx/templates
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      #- NGINX_HOST=124.223.74.196
      - NGINX_PORT=80