server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;  # 确保SPA的路由可以正常工作
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location /api1 {
	  proxy_pass http://host.docker.internal:8888/api1;
	}
	location /login {
	    proxy_pass http://host.docker.internal:2022/login;
    }
    location /home {
        proxy_pass http://host.docker.internal:2022/home;
    }
    location /edit_profile {
        proxy_pass http://host.docker.internal:2022/edit_profile;
    }
    location /user_list{
        proxy_pass http://host.docker.internal:2022/user_list;
    }
    location /register {
        proxy_pass http://host.docker.internal:2022/register;
    }
    location /static {
        proxy_pass http://host.docker.internal:2022/static;
    }
    location /ws {
        proxy_pass http://host.docker.internal:2022/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket 连接可能会长时间保持，需要设置较长的超时时间
        proxy_read_timeout 36000s;
        proxy_send_timeout 36000s;
        }
# 	location /api2 {
# 	  proxy_pass http://124.223.74.196/api2;
# 	}
# 	location /api3 {
# 	  proxy_pass http://124.223.74.196/api3;
# 	}
# 	location /api4 {
# 	  proxy_pass http://124.223.74.196/api4;
# 	}

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

