# 使用Alpine镜像作为基础镜像
FROM alpine:latest

# 创建应用工作目录和配置目录
RUN mkdir -p /app && mkdir -p /app/judgeStatus/cmd/rpc/etc

# 将本地编译好的二进制文件复制到容器中
COPY rpc/judge-rpc /app/judge-rpc

# 设置工作目录
WORKDIR /app

# 设置容器启动时执行的命令
CMD ["./judge-rpc"]

# 暴露容器服务端口
EXPOSE 8082