// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	problem_data "oj-micro/problems/cmd/api/internal/handler/problem_data"
	problems "oj-micro/problems/cmd/api/internal/handler/problems"
	tags "oj-micro/problems/cmd/api/internal/handler/tags"
	test_case "oj-micro/problems/cmd/api/internal/handler/test_case"
	"oj-micro/problems/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/problems_data",
				Handler: problem_data.SearchProblemsDataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/problems_data/:problem_data_id",
				Handler: problem_data.GetProblemDataHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/problems_data/update",
				Handler: problem_data.UpdateProblemDataHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/problems",
				Handler: problems.AddProblemHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/problems/delete",
				Handler: problems.DeleteProblemHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/problems/update",
				Handler: problems.UpdateProblemHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/problems",
				Handler: problems.SearchProblemsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/problems/:problem_id",
				Handler: problems.GetProblemByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/problems/tag/:tag_id",
				Handler: problems.ListProblemsByTagIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/tags",
				Handler: tags.AddTagHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tags/delete",
				Handler: tags.DeleteTagHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tags/update",
				Handler: tags.UpdateTagHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tags",
				Handler: tags.SearchTagsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tags/:tag_id",
				Handler: tags.GetTagByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tags/problem/:problem_id",
				Handler: tags.ListTagsByProblemIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/test_cases",
				Handler: test_case.SearchTestCasesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/test_cases/:test_id",
				Handler: test_case.GetTestCaseByIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api2"),
	)
}
