# 主库配置
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
spec:
  type: ClusterIP  # 确保使用ClusterIP类型
  ports:
    - port: 3306        # Service暴露的端口
      targetPort: 3306  # MySQL的端口
#  clusterIP: None       # 这是一个Headless Service
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-master    # 必须与 Service 名称相同
subsets:
  - addresses:
      - ip: 124.223.74.196  # 替换为你的主库实际IP
    ports:
      - port: 3306
---
# 从库配置
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
spec:
  type: ClusterIP  # 确保使用ClusterIP类型
  ports:
    - port: 3306
      targetPort: 3306
#  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-slave    # 必须与 Service 名称相同
subsets:
  - addresses:
      - ip: 8.134.142.46  # 替换为你的从库实际IP
    ports:
      - port: 3306