services:
  problems-rpc:
    build:
      context: ../cmd # 指定Dockerfile的目录
      dockerfile: Dockerfile-problems_rpc           # Dockerfile的名称（如果不是默认的）
    image: problems-rpc:v1.2
    container_name: oj-problems-rpc
    networks:
      - oj-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    ports:
#      - "8081:8081"
    volumes:
      - ./:/app/problems/cmd/rpc/etc
      - ./logs/rpc:/app/problems/cmd/rpc/logs

  problems-api:
    build:
      context: ../cmd # 指定Dockerfile的目录
      dockerfile: Dockerfile-problems_api           # Dockerfile的名称（如果不是默认的）
    image: problems-api:v1.1
    container_name: oj-problems-api
    networks:
      - oj-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8889:8889" # 假设您的Go应用监听在8089端口
    depends_on:
      - problems-rpc
    volumes:
      - ./:/app/problems/cmd/api/etc
      - ./logs/api:/app/problems/cmd/api/logs

networks:
  oj-network:
    external: true