// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"oj-micro/users/cmd/rpc/internal/logic"
	"oj-micro/users/cmd/rpc/internal/svc"
	"oj-micro/users/cmd/rpc/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------用户认证授权-----------------------
func (s *UserServiceServer) AddUserLogin(ctx context.Context, in *pb.AddUserLoginReq) (*pb.AddUserLoginResp, error) {
	l := logic.NewAddUserLoginLogic(ctx, s.svcCtx)
	return l.AddUserLogin(in)
}

func (s *UserServiceServer) UpdateUserLogin(ctx context.Context, in *pb.UpdateUserLoginReq) (*pb.UpdateUserLoginResp, error) {
	l := logic.NewUpdateUserLoginLogic(ctx, s.svcCtx)
	return l.UpdateUserLogin(in)
}

func (s *UserServiceServer) DelUserLogin(ctx context.Context, in *pb.DelUserLoginReq) (*pb.DelUserLoginResp, error) {
	l := logic.NewDelUserLoginLogic(ctx, s.svcCtx)
	return l.DelUserLogin(in)
}

func (s *UserServiceServer) GetUserLoginById(ctx context.Context, in *pb.GetUserLoginByIdReq) (*pb.GetUserLoginByIdResp, error) {
	l := logic.NewGetUserLoginByIdLogic(ctx, s.svcCtx)
	return l.GetUserLoginById(in)
}

func (s *UserServiceServer) SearchUserLogin(ctx context.Context, in *pb.SearchUserLoginReq) (*pb.SearchUserLoginResp, error) {
	l := logic.NewSearchUserLoginLogic(ctx, s.svcCtx)
	return l.SearchUserLogin(in)
}

func (s *UserServiceServer) LoginUser(ctx context.Context, in *pb.LoginUserReq) (*pb.LoginUserResp, error) {
	l := logic.NewLoginUserLogic(ctx, s.svcCtx)
	return l.LoginUser(in)
}

func (s *UserServiceServer) LoginWithCode(ctx context.Context, in *pb.LoginWithCodeReq) (*pb.LoginUserResp, error) {
	l := logic.NewLoginWithCodeLogic(ctx, s.svcCtx)
	return l.LoginWithCode(in)
}

func (s *UserServiceServer) PartialUpdateUser(ctx context.Context, in *pb.PartialUpdateUserReq) (*pb.PartialUpdateUserResp, error) {
	l := logic.NewPartialUpdateUserLogic(ctx, s.svcCtx)
	return l.PartialUpdateUser(in)
}

// -----------------------用户信息-----------------------
func (s *UserServiceServer) UpdateUserProfile(ctx context.Context, in *pb.UpdateUserProfileReq) (*pb.UpdateUserProfileResp, error) {
	l := logic.NewUpdateUserProfileLogic(ctx, s.svcCtx)
	return l.UpdateUserProfile(in)
}

// rpc DelUserProfile(DelUserProfileReq) returns (DelUserProfileResp);
func (s *UserServiceServer) GetUserProfileById(ctx context.Context, in *pb.GetUserProfileByIdReq) (*pb.GetUserProfileByIdResp, error) {
	l := logic.NewGetUserProfileByIdLogic(ctx, s.svcCtx)
	return l.GetUserProfileById(in)
}

func (s *UserServiceServer) SearchUserProfile(ctx context.Context, in *pb.SearchUserProfileReq) (*pb.SearchUserProfileResp, error) {
	l := logic.NewSearchUserProfileLogic(ctx, s.svcCtx)
	return l.SearchUserProfile(in)
}

func (s *UserServiceServer) GetRankByUserId(ctx context.Context, in *pb.GetRankByUserIdReq) (*pb.GetRankByUserIdResp, error) {
	l := logic.NewGetRankByUserIdLogic(ctx, s.svcCtx)
	return l.GetRankByUserId(in)
}
