// Code generated by goctl. DO NOT EDIT.
// Source: judgestatus.proto

package server

import (
	"context"

	"oj-micro/judgeStatus/cmd/rpc/internal/logic"
	"oj-micro/judgeStatus/cmd/rpc/internal/svc"
	"oj-micro/judgeStatus/cmd/rpc/pb"
)

type JudgeServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedJudgeServiceServer
}

func NewJudgeServiceServer(svcCtx *svc.ServiceContext) *JudgeServiceServer {
	return &JudgeServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------judgestatus-----------------------
func (s *JudgeServiceServer) AddJudgestatus(in *pb.AddJudgestatusReq, stream pb.JudgeService_AddJudgestatusServer) error {
	l := logic.NewAddJudgestatusLogic(stream.Context(), s.svcCtx)
	return l.AddJudgestatus(in, stream)
}

func (s *JudgeServiceServer) UpdateJudgestatus(ctx context.Context, in *pb.UpdateJudgestatusReq) (*pb.UpdateJudgestatusResp, error) {
	l := logic.NewUpdateJudgestatusLogic(ctx, s.svcCtx)
	return l.UpdateJudgestatus(in)
}

func (s *JudgeServiceServer) DelJudgestatus(ctx context.Context, in *pb.DelJudgestatusReq) (*pb.DelJudgestatusResp, error) {
	l := logic.NewDelJudgestatusLogic(ctx, s.svcCtx)
	return l.DelJudgestatus(in)
}

func (s *JudgeServiceServer) GetJudgestatusById(ctx context.Context, in *pb.GetJudgestatusByIdReq) (*pb.GetJudgestatusByIdResp, error) {
	l := logic.NewGetJudgestatusByIdLogic(ctx, s.svcCtx)
	return l.GetJudgestatusById(in)
}

func (s *JudgeServiceServer) SearchJudgestatus(ctx context.Context, in *pb.SearchJudgestatusReq) (*pb.SearchJudgestatusResp, error) {
	l := logic.NewSearchJudgestatusLogic(ctx, s.svcCtx)
	return l.SearchJudgestatus(in)
}
