apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-api-config
data:
  upload-api.yaml: |
    Name: upload-api
    Host: 0.0.0.0
    Port: 8890
    MaxBytes: 41943040 # 40MB
    Timeout: 10000

    log:
      Level: info
      Encoding: plain
      Mode: file
      Path: other/logs

    Auth:
      AccessSecret: ae0536f9-6450-4606-8e13-5a19ed505da0
      AccessExpire: 31536000

    UploadConfigs:
      ImageLimit:
        MaxSize: 5 #MB
        AllowExts:
          - .jpg
          - .jpeg
          - .png
      SampleIOLimit:
        MaxSize: 20 #MB
        AllowExts:
          - .in
          - .out
          - .txt

    MinioConfig:
      Endpoints:
        - 10.43.93.18:9000
        - 10.43.93.17:9000
      BucketName: oj-file
      AccessKeyID: minio
      AccessKeySecret: miniosecret
      DomainName: http://124.223.74.196

    ProblemRpcConf:
      Etcd:
        Hosts:
          - 10.43.241.133:2379
        Key: problem.rpc
      NonBlock: true

    UserRpcConf:
      Etcd:
        Hosts:
          - 10.43.241.133:2379
        Key: user.rpc
      NonBlock: true
      
