apiVersion: v1
kind: ConfigMap
metadata:
  name: judgestatus-api-config
data:
  judgestatus-api.yaml: |
    Name: judgeStatus-api
    Host: 0.0.0.0
    Port: 8891
    Timeout: 10000

    log:
      Level: info
      Encoding: plain
      Mode: file
      Path: judgeStatus/cmd/api/logs

    Auth:
      AccessSecret: ae0536f9-6450-4606-8e13-5a19ed505da0
      AccessExpire: 31536000

    JudgeStatusRpcConf:
      Etcd:
        Hosts:
          - 10.43.241.133:2379
        Key: judgestatus.rpc
        NonBlock: true

    ProblemRpcConf:
      Etcd:
        Hosts:
          - 10.43.241.133:2379
        Key: problem.rpc
      NonBlock: true